FROM webdevops/php-nginx

MAINTAINER Kamil Zajac <kaz231@outlook.com>

ENV WEB_DOCUMENT_ROOT  /app/web
ENV WEB_DOCUMENT_INDEX app.php

COPY ./ /app/

RUN chown -R application:application /app

WORKDIR /app

EXPOSE 80
