FROM webdevops/php-nginx

MAINTAINER Kamil Zajac <kaz231@outlook.com>

ENV WEB_DOCUMENT_ROOT  /app/web
ENV WEB_DOCUMENT_INDEX app.php

WORKDIR /app

COPY var/00-symfony.conf /opt/docker/etc/nginx/vhost.common.d/00-symfony.conf

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('SHA384', 'composer-setup.php') === 'aa96f26c2b67226a324c27919f1eb05f21c248b987e6195cad9690d5c1ff713d53020a02ac8c217dbf90a7eacc9d141d') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && service nginx restart

RUN usermod -u 900 application

EXPOSE 80
