services:
    session.memcached:
        class: Memcached
        arguments:
            - "%%session_memcached_prefix%%"
        calls:
            - [ addServer, [ "%session_memcached_host%", "%session_memcached_port%" ] ]

    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ["@session.memcached", { prefix: "%session_memcached_prefix%", expiretime: "%session_memcached_expire%"}]