services:
    tracker.message_bus.collects_events:
        class: TrackerBundle\Message\Bus\Middleware\CollectsEventMiddleware
        tags:
            - { name: event_bus_middleware }

    tracker.message_bus.catches_exceptions:
        class: TrackerBundle\Message\Bus\Middleware\CatchesExceptionMiddleware
        tags:
            - { name: command_bus_middleware }